import { useState, useEffect, useCallback } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import { revealItemInDir } from "@tauri-apps/plugin-opener";
import ScrambleText from "../components/ScrambleText";
import LogPanel from "../components/LogPanel";
import Dropdown from "../components/Dropdown";
import {
  useDownloadStore,
  bindDownloadEvents,
  QUALITY_OPTIONS,
  AUDIO_FORMAT_OPTIONS,
  OUTPUT_FORMAT_OPTIONS,
} from "../store/downloadStore";
import { useContextMenu } from "../components/ContextMenu";
import type { DownloadOptions, DownloadQuality } from "../types";

function isValidUrl(text: string): boolean {
  try {
    const u = new URL(text);
    return u.protocol === "http:" || u.protocol === "https:";
  } catch {
    return false;
  }
}

function fmtSize(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)}KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)}MB`;
}

function fmtDuration(seconds: number): string {
  if (seconds <= 0) return "—";
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

export default function ImportPage() {
  const {
    available,
    downloadsDir,
    installing,
    installProgress,
    metadata,
    fetching,
    downloading,
    downloadProgress,
    downloadLog,
    recentDownloads,
    loadingDownloads,
    error,
    init,
    installYtdlp,
    fetchMetadata,
    startDownload,
    cancelDownload,
    loadRecentDownloads,
    deleteDownload,
    clearError,
    resetLog,
  } = useDownloadStore();

  const { show } = useContextMenu();

  const [url, setUrl] = useState("");
  const [quality, setQuality] = useState<DownloadQuality>("best");
  const [audioFormat, setAudioFormat] = useState("mp3");
  const [outputFormat, setOutputFormat] = useState("");
  const [downloadSubs, setDownloadSubs] = useState(false);
  const [embedSubs, setEmbedSubs] = useState(false);
  const [selectedSubLangs, setSelectedSubLangs] = useState<string[]>([]);
  const [playlistItems, setPlaylistItems] = useState("");
  const [outputDir, setOutputDir] = useState("");
  const [btnHover, setBtnHover] = useState(false);
  const [recentOpen, setRecentOpen] = useState(false);

  // ── Bootstrap ──
  useEffect(() => {
    init();
    bindDownloadEvents();
    loadRecentDownloads();
  }, [init, loadRecentDownloads]);

  // ── Default output dir ──
  useEffect(() => {
    if (!outputDir && downloadsDir) {
      setOutputDir(downloadsDir);
    }
  }, [downloadsDir, outputDir]);

  // ── Auto-select first subtitle track when metadata arrives ──
  useEffect(() => {
    if (metadata && metadata.subtitles.length > 0) {
      const preferred =
        metadata.subtitles.find((s) => !s.autoGenerated) ?? metadata.subtitles[0];
      setSelectedSubLangs([preferred.language]);
    }
  }, [metadata]);

  // ── Auto-fetch metadata when URL changes (debounced) ──
  useEffect(() => {
    const trimmed = url.trim();
    if (!isValidUrl(trimmed)) return;
    const timer = setTimeout(() => {
      fetchMetadata(trimmed);
    }, 600);
    return () => clearTimeout(timer);
  }, [url, fetchMetadata]);

  // ── Handlers ──
  const handlePaste = useCallback(async () => {
    try {
      const text = await navigator.clipboard.readText();
      if (text) {
        const trimmed = text.trim();
        setUrl(trimmed);
        if (isValidUrl(trimmed)) {
          await fetchMetadata(trimmed);
        }
      }
    } catch {
      // clipboard unavailable
    }
  }, [fetchMetadata]);

  const browseOutputDir = useCallback(async () => {
    const sel = await open({ directory: true, multiple: false });
    if (sel) setOutputDir(sel as string);
  }, []);

  const handleDownload = useCallback(async () => {
    if (!metadata) return;
    const options: DownloadOptions = {
      url: metadata.url || url.trim(),
      outputDir: outputDir || downloadsDir,
      mediaType: quality === "audio_only" ? "audio" : "video",
      formatId: undefined,
      quality,
      downloadSubtitles: downloadSubs,
      subtitleLanguages: selectedSubLangs,
      embedSubtitles: embedSubs,
      extractAudio: quality === "audio_only",
      audioFormat: quality === "audio_only" ? audioFormat : undefined,
      playlistItems: metadata.isPlaylist ? playlistItems || undefined : undefined,
      outputFormat: quality === "audio_only" ? undefined : (outputFormat || undefined),
    };
    await startDownload(options);
  }, [metadata, url, outputDir, downloadsDir, quality, downloadSubs, selectedSubLangs, embedSubs, audioFormat, outputFormat, playlistItems, startDownload]);

  const handleCancel = useCallback(async () => {
    await cancelDownload();
  }, [cancelDownload]);

  const handleDelete = useCallback(async (path: string) => {
    await deleteDownload(path);
  }, [deleteDownload]);

  // ── Context menus ──
  const handleUrlContext = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    show(e, [
      { label: "paste url", rune: "ᚷ", action: handlePaste },
      { label: "clear", rune: "ᚨ", action: () => setUrl("") },
    ]);
  }, [show, handlePaste]);

  const handleOutputContext = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    show(e, [
      { label: "browse", rune: "ᚨ", action: browseOutputDir },
      { label: "copy path", rune: "ᚷ", action: () => navigator.clipboard.writeText(outputDir) },
      ...(outputDir ? [{ label: "clear", rune: "ᚨ", action: () => setOutputDir("") }] : []),
    ]);
  }, [show, outputDir, browseOutputDir]);

  const handleLogContext = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    if (downloadLog.length === 0) return;
    show(e, [
      { label: "copy all", rune: "ᚷ", action: () => navigator.clipboard.writeText(downloadLog.join("\n")) },
      { label: "clear", rune: "ᚨ", action: () => resetLog() },
    ]);
  }, [show, downloadLog, resetLog]);

  // ── Derived ──
  const urlValid = isValidUrl(url.trim());
  const canDownload = !!metadata && !downloading && !installing && available;
  const progress = downloadProgress?.progress ?? 0;
  const isRunning = downloading || installing;

  return (
    <div className="page import-page">
      {/* ── yt-dlp install banner (compact, single line) ── */}
      {!available && (
        <div className="import-install-bar">
          <span className="import-install-text">yt-dlp required</span>
          <button
            className="btn"
            disabled={installing}
            onClick={installYtdlp}
          >
            {installing
              ? `installing ${((installProgress?.progress ?? 0) * 100).toFixed(0)}%`
              : "install"}
          </button>
          <span className="import-install-hint">~15 MB from GitHub</span>
        </div>
      )}

      {/* ── URL input ── */}
      <div className="section-heading">
        <span className="section-heading-line" />
        <span className="section-heading-rune">ᛣ</span>
        <span className="section-heading-label">url</span>
      </div>

      <div className="card" onContextMenu={handleUrlContext}>
        <div className="row">
          <input
            className="input import-url-input"
            value={url}
            placeholder="paste a URL…"
            onChange={(e) => setUrl(e.target.value)}
          />
          <button className="btn" onClick={handlePaste} title="paste from clipboard">
            paste
          </button>
        </div>
        {fetching && <div className="import-hint">fetching…</div>}
        {!urlValid && url.length > 0 && !fetching && (
          <div className="import-hint">! invalid URL</div>
        )}
      </div>

      {/* ── Metadata card ── */}
      {metadata && (
        <>
          <div className="section-heading">
            <span className="section-heading-line" />
            <span className="section-heading-rune">ᚨ</span>
            <span className="section-heading-label">info</span>
          </div>

          <div className="card import-metadata">
            {metadata.thumbnail && (
              <img
                className="import-thumb"
                src={metadata.thumbnail}
                alt=""
                referrerPolicy="no-referrer"
              />
            )}
            <div className="import-meta-body">
              <div className="import-meta-title">{metadata.title}</div>
              {metadata.uploader && (
                <div className="import-meta-uploader">{metadata.uploader}</div>
              )}
              <div className="import-meta-stats">
                <span>⏱ {fmtDuration(metadata.duration)}</span>
                {metadata.isPlaylist && (
                  <span className="import-playlist-badge">
                    playlist · {metadata.playlistCount ?? "?"}
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* ── Quality ── */}
          <div className="section-heading">
            <span className="section-heading-line" />
            <span className="section-heading-rune">ᛟ</span>
            <span className="section-heading-label">options</span>
          </div>

          <div className="card">
            <label className="label">quality</label>
            <Dropdown
              options={QUALITY_OPTIONS.map((q) => ({ value: q.value, label: q.label }))}
              value={quality}
              onChange={(v) => setQuality(v as DownloadQuality)}
            />
            {quality === "audio_only" ? (
              <>
                <label className="label" style={{ marginTop: 10 }}>audio format</label>
                <Dropdown
                  options={AUDIO_FORMAT_OPTIONS}
                  value={audioFormat}
                  onChange={setAudioFormat}
                />
              </>
            ) : (
              <>
                <label className="label" style={{ marginTop: 10 }}>container</label>
                <Dropdown
                  options={OUTPUT_FORMAT_OPTIONS}
                  value={outputFormat}
                  onChange={setOutputFormat}
                />
              </>
            )}
          </div>

          {/* ── Subtitles ── */}
          {metadata.subtitles.length > 0 && (
            <div className="card">
              <label className="label">subs ({metadata.subtitles.length})</label>
              <div className="row settings-toggle-row">
                <label className="toggle-label">download</label>
                <button
                  className={`btn toggle-btn${downloadSubs ? " active" : ""}`}
                  onClick={() => setDownloadSubs((v) => !v)}
                >
                  {downloadSubs ? "on" : "off"}
                </button>
              </div>
              {downloadSubs && (
                <>
                  <div className="import-sub-langs">
                    {metadata.subtitles.map((s) => {
                      const checked = selectedSubLangs.includes(s.language);
                      return (
                        <button
                          key={s.language}
                          className={`btn import-sub-lang-btn${checked ? " active" : ""}`}
                          onClick={() => {
                            setSelectedSubLangs((prev) =>
                              checked
                                ? prev.filter((l) => l !== s.language)
                                : [...prev, s.language]
                            );
                          }}
                        >
                          {s.name}
                          {s.autoGenerated && <span className="import-sub-auto"> auto</span>}
                        </button>
                      );
                    })}
                  </div>
                  <div className="row settings-toggle-row">
                    <label className="toggle-label">embed</label>
                    <button
                      className={`btn toggle-btn${embedSubs ? " active" : ""}`}
                      onClick={() => setEmbedSubs((v) => !v)}
                    >
                      {embedSubs ? "on" : "off"}
                    </button>
                  </div>
                </>
              )}
            </div>
          )}

          {/* ── Playlist ── */}
          {metadata.isPlaylist && (
            <div className="card">
              <label className="label">items</label>
              <div className="row">
                <input
                  className="input import-url-input"
                  value={playlistItems}
                  placeholder="1-5, 8 (empty = all)"
                  onChange={(e) => setPlaylistItems(e.target.value)}
                />
              </div>
            </div>
          )}

          {/* ── Output folder ── */}
          <div className="card" onContextMenu={handleOutputContext}>
            <label className="label">save to</label>
            <div className="row">
              <input className="input" value={outputDir} placeholder="downloads folder" readOnly />
              <button className="btn" onClick={browseOutputDir}>browse</button>
            </div>
          </div>

          {/* ── Download action ── */}
          <div className="convert-actions">
            <button
              className="btn btn-primary"
              disabled={!canDownload}
              onClick={handleDownload}
              onMouseEnter={() => setBtnHover(true)}
              onMouseLeave={() => setBtnHover(false)}
            >
              {downloading
                ? "downloading…"
                : <ScrambleText text="download" trigger={btnHover} ticks={4} />}
            </button>
            {downloading && (
              <button className="btn btn-cancel" onClick={handleCancel} title="cancel">
                ■
              </button>
            )}
          </div>
        </>
      )}

      {/* ── Progress ── */}
      {isRunning && (
        <div className="progress-bar-container">
          <div className="progress-bar" style={{ width: `${(installing ? (installProgress?.progress ?? 0) : progress) * 100}%` }} />
          <span className="progress-text">
            {installing
              ? "installing yt-dlp…"
              : `${(progress * 100).toFixed(0)}%${downloadProgress?.speed ? " · " + downloadProgress.speed : ""}`
            }
          </span>
        </div>
      )}

      {/* ── Log ── */}
      {downloadLog.length > 0 && (
        <LogPanel lines={downloadLog} onContextMenu={handleLogContext} />
      )}

      {/* ── Error ── */}
      {error && (
        <div className="alert-error" onClick={() => clearError()} style={{ cursor: "pointer" }}>
          ! {error}
        </div>
      )}

      {/* ── Recent downloads ── */}
      <div className="section-heading import-recent-heading" onClick={() => setRecentOpen((o) => !o)}>
        <span className="section-heading-line" />
        <span className="section-heading-rune">{recentOpen ? "▾" : "▸"}</span>
        <span className="section-heading-label">recent ({recentDownloads.length})</span>
      </div>

      {recentOpen && (
        <div className="import-recent">
          {loadingDownloads && <div className="import-hint">loading…</div>}
          {!loadingDownloads && recentDownloads.length === 0 && (
            <div className="import-hint">no downloads yet</div>
          )}
          {recentDownloads.map((f) => (
            <div key={f.path} className="import-recent-row">
              <span className="import-recent-name" title={f.path}>
                ᛣ {f.name}
              </span>
              <span className="import-recent-size">{fmtSize(f.size)}</span>
              <div className="import-recent-actions">
                <button className="btn" onClick={() => revealItemInDir(f.path)}>
                  show
                </button>
                <button className="btn import-recent-delete" onClick={() => handleDelete(f.path)} title="delete">
                  ✕
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
