export interface FormatOption {
  value: string;
  label: string;
  type: "video" | "audio" | "image";
  category: string;
}

export const FORMAT_OPTIONS: FormatOption[] = [
  { value: "mp4", label: "mp4 (video)", type: "video", category: "video" },
  { value: "mkv", label: "mkv (video)", type: "video", category: "video" },
  { value: "avi", label: "avi (video)", type: "video", category: "video" },
  { value: "mov", label: "mov (video)", type: "video", category: "video" },
  { value: "webm", label: "webm (video)", type: "video", category: "video" },
  { value: "m4v", label: "m4v (video)", type: "video", category: "video" },
  { value: "flv", label: "flv (video)", type: "video", category: "video" },
  { value: "ogv", label: "ogv (video)", type: "video", category: "video" },
  { value: "wmv", label: "wmv (video)", type: "video", category: "video" },
  { value: "gif", label: "gif (video)", type: "video", category: "video" },
  { value: "mod", label: "mod (video)", type: "video", category: "video" },
  { value: "mp3", label: "mp3 (audio)", type: "audio", category: "audio" },
  { value: "flac", label: "flac (audio)", type: "audio", category: "audio" },
  { value: "wav", label: "wav (audio)", type: "audio", category: "audio" },
  { value: "aac", label: "aac (audio)", type: "audio", category: "audio" },
  { value: "ogg", label: "ogg (audio)", type: "audio", category: "audio" },
  { value: "opus", label: "opus (audio)", type: "audio", category: "audio" },
  { value: "wma", label: "wma (audio)", type: "audio", category: "audio" },
  { value: "m4a", label: "m4a (audio)", type: "audio", category: "audio" },
  { value: "aiff", label: "aiff (audio)", type: "audio", category: "audio" },
  { value: "ac3", label: "ac3 (audio)", type: "audio", category: "audio" },
  { value: "png", label: "png (image)", type: "image", category: "image" },
  { value: "jpeg", label: "jpeg (image)", type: "image", category: "image" },
  { value: "webp", label: "webp (image)", type: "image", category: "image" },
  { value: "bmp", label: "bmp (image)", type: "image", category: "image" },
  { value: "tiff", label: "tiff (image)", type: "image", category: "image" },
  { value: "avif", label: "avif (image)", type: "image", category: "image" },
];

export const EXT_OPTIONS: FormatOption[] = [
  { value: "mp4", label: ".mp4", type: "video", category: "video" },
  { value: "mkv", label: ".mkv", type: "video", category: "video" },
  { value: "avi", label: ".avi", type: "video", category: "video" },
  { value: "mov", label: ".mov", type: "video", category: "video" },
  { value: "webm", label: ".webm", type: "video", category: "video" },
  { value: "m4v", label: ".m4v", type: "video", category: "video" },
  { value: "flv", label: ".flv", type: "video", category: "video" },
  { value: "ogv", label: ".ogv", type: "video", category: "video" },
  { value: "wmv", label: ".wmv", type: "video", category: "video" },
  { value: "ts", label: ".ts", type: "video", category: "video" },
  { value: "3gp", label: ".3gp", type: "video", category: "video" },
  { value: "mod", label: ".mod", type: "video", category: "video" },
  { value: "mp3", label: ".mp3", type: "audio", category: "audio" },
  { value: "flac", label: ".flac", type: "audio", category: "audio" },
  { value: "wav", label: ".wav", type: "audio", category: "audio" },
  { value: "aac", label: ".aac", type: "audio", category: "audio" },
  { value: "ogg", label: ".ogg", type: "audio", category: "audio" },
  { value: "opus", label: ".opus", type: "audio", category: "audio" },
  { value: "wma", label: ".wma", type: "audio", category: "audio" },
  { value: "m4a", label: ".m4a", type: "audio", category: "audio" },
  { value: "aiff", label: ".aiff", type: "audio", category: "audio" },
  { value: "ac3", label: ".ac3", type: "audio", category: "audio" },
  { value: "dts", label: ".dts", type: "audio", category: "audio" },
  { value: "png", label: ".png", type: "image", category: "image" },
  { value: "jpg", label: ".jpg", type: "image", category: "image" },
  { value: "jpeg", label: ".jpeg", type: "image", category: "image" },
  { value: "webp", label: ".webp", type: "image", category: "image" },
  { value: "gif", label: ".gif", type: "image", category: "image" },
  { value: "bmp", label: ".bmp", type: "image", category: "image" },
  { value: "tiff", label: ".tiff", type: "image", category: "image" },
  { value: "avif", label: ".avif", type: "image", category: "image" },
  { value: "svg", label: ".svg", type: "image", category: "image" },
];

export const FMT_OPTIONS: FormatOption[] = [
  { value: "mp4", label: "mp4", type: "video", category: "video" },
  { value: "mkv", label: "mkv", type: "video", category: "video" },
  { value: "avi", label: "avi", type: "video", category: "video" },
  { value: "mov", label: "mov", type: "video", category: "video" },
  { value: "webm", label: "webm", type: "video", category: "video" },
  { value: "m4v", label: "m4v", type: "video", category: "video" },
  { value: "flv", label: "flv", type: "video", category: "video" },
  { value: "ogv", label: "ogv", type: "video", category: "video" },
  { value: "wmv", label: "wmv", type: "video", category: "video" },
  { value: "gif", label: "gif", type: "video", category: "video" },
  { value: "mod", label: "mod", type: "video", category: "video" },
  { value: "mp3", label: "mp3", type: "audio", category: "audio" },
  { value: "flac", label: "flac", type: "audio", category: "audio" },
  { value: "wav", label: "wav", type: "audio", category: "audio" },
  { value: "aac", label: "aac", type: "audio", category: "audio" },
  { value: "ogg", label: "ogg", type: "audio", category: "audio" },
  { value: "opus", label: "opus", type: "audio", category: "audio" },
  { value: "wma", label: "wma", type: "audio", category: "audio" },
  { value: "m4a", label: "m4a", type: "audio", category: "audio" },
  { value: "aiff", label: "aiff", type: "audio", category: "audio" },
  { value: "ac3", label: "ac3", type: "audio", category: "audio" },
  { value: "png", label: "png", type: "image", category: "image" },
  { value: "jpeg", label: "jpeg", type: "image", category: "image" },
  { value: "webp", label: "webp", type: "image", category: "image" },
  { value: "bmp", label: "bmp", type: "image", category: "image" },
  { value: "tiff", label: "tiff", type: "image", category: "image" },
  { value: "avif", label: "avif", type: "image", category: "image" },
];

/** Pre-defined encoder selection options for the Settings → Encoding dropdown. */
export const ENCODER_OPTIONS: { value: string; label: string }[] = [
  { value: "auto", label: "Auto (prefer hardware, fallback to software)" },
  { value: "software", label: "Software encoding only" },
];
